### ISSUE TITLE
Datasets

### ISSUE THREAD

**Issue by hjs2027864933** [deeplearning-wisc/MCM#1]
Thank you very much for your great work, I found out while trying to implement your code that it produces an error when testing the CUB-200 dataset:
```
FileNotFoundError: [Errno 2] No such file or directory: 'datasets/CUB_200_2011/images.txt'.
```
I found that the reason for the error is that your code does not automatically download this dataset as you said in the README file. When I manually went to the official website to download the dataset, the code could run successfully. Maybe it's a small mistake, but hope it helps, thanks again for the great work.

**Comment by hjs2027864933** [comment]
Thanks for the great work, when I run this command:
```
 sh scripts/eval_mcm.sh eval_ood ImageNet MCM
```
The following error was generated: 
```
FileNotFoundError: [Errno 2] No such file or directory: 'data/ImageNet/imagenet_class_clean.npy'.
```
I did not find this .npy file.
Another question is, how do I need to generate the three datasets ImageNet10, ImageNet-20 and ImageNet-100? I didn't find the relevant code.
Thanks again for your great work and hope to hear back from you.

**Comment by alvinmingsf** [comment]
Thanks a lot for pointing out the issues and support for our work! I have just updated imagenet_class_clean.npy under data/ImageNet. Instructions for CUB-200 are also updated in Readme. Now the script should work. Please let me know if there are any remaining issues.

**Comment by alvinmingsf** [comment]
ImageNet10, ImageNet-20 and ImageNet-100 can be subsampled from ImageNet-1k given the class IDs in the csv file. I will also upload a script for generating each dataset. Please stay tuned.

**Comment by hjs2027864933** [comment]
> Thanks a lot for pointing out the issues and support for our work! I have just updated imagenet_class_clean.npy under data/ImageNet. Now the script should work. Please let me know if there are any remaining issues.

Your reply is efficient, thank you for your reply! The script is now working fine.

**Comment by hjs2027864933** [comment]
> ImageNet10, ImageNet-20 and ImageNet-100 can be subsampled from ImageNet-1k given the class IDs in the csv file. I will also upload a script for generating each dataset in a day or two. Please stay tuned.

Okay, waiting for your good news.

**Comment by alvinmingsf** [comment]
Thanks for your patience. Please check the script named _create_imagenet_subset.py_. I also updated Readme for relevant commands.
