### ISSUE TITLE
Axis = 1 is missing?

### ISSUE THREAD

**Issue by JiuqingDong** [deeplearning-wisc/MCM#12]
https://github.com/deeplearning-wisc/MCM/blob/672214188694572556caff9b5aa21d89815b62ed/utils/detection_util.py#L243C21-L243C21

I have found a mistake, so I would like to verify it with you.

Here, did you miss including a parameter axis=1? 
I think it should be "_score.append(entropy(smax, axis = 1)) "

**Comment by alvinmingsf** [comment]
Hi! Thanks for flagging the issue! Yes, it should be axis = 1 inside scipy.stats.entropy(). Script updated.
