### ISSUE TITLE
Info on imagenet_class_clean.npy

### ISSUE THREAD

**Issue by MarcLafon** [deeplearning-wisc/MCM#13]
Hi, could you provide more information on how the Imagenet class labels have been cleaned up in the [imagenet_class_clean.npy](https://github.com/deeplearning-wisc/MCM/tree/main/data/ImageNet) file ? I guess it is necessary to change a bit class labels in order for CLIP to give a good representation (ex: "admiral" --> "red admiral butterfly"). Thank you.

**Comment by alvinmingsf** [comment]
Yes, I agree. The cleaned class names can be found here: https://github.com/openai/CLIP/blob/main/notebooks/Prompt_Engineering_for_ImageNet.ipynb. It's possible that they manually adjusted the names to enhance CLIP's performance.
