### ISSUE TITLE
Reproduce experimental results

### ISSUE THREAD

**Issue by burgerberlin** [deeplearning-wisc/MCM#15]
Dear Author,

I hope this message finds you well. I am writing to discuss some challenges I encountered while attempting to reproduce the experimental results presented in your research paper. I have followed the methodology outlined in the paper and utilized the model available at the following URL: https://huggingface.co/openai/clip-vit-base-patch16.

To replicate the results, I utilized the imagenet-1k dataset as the input data. While I successfully obtained matching results for texture-related evaluations, I observed discrepancies in the performance metrics for places365 and iNaturalist datasets. Specifically, the obtained AUROC and FPR95 values for places365 were 86.13 and 56.92 respectively, whereas for iNaturalist, the AUROC and FPR95 values were 68.44 and 77.19 respectively. These results differ from the values reported in your paper.

I would greatly appreciate your guidance in understanding the potential factors that might have contributed to these discrepancies. I have maintained the default settings for all other experimental configurations, except the model loaded due to my Internet connection. I download the model from the url above in advance instead of directly downloading it while the code run. Additionally, I would like to seek clarification regarding the concept of softmax scaling as mentioned in your paper. Specifically, I am curious to know if there is any distinction between setting tau=1 and employing the original softmax function.

I am eager to receive your response and insights on these matters. Thank you in advance for your time and attention to this matter. Your guidance will be instrumental in ensuring the accurate reproduction of your research findings.
Thank you once again, and I look forward to hearing from you soon.

**Comment by alvinmingsf** [comment]
Thanks for your interest in our work! 

If the Textures results match but iNaturalist and Places365 do not, have you used the OOD test sets created by Huang et al.  (https://github.com/deeplearning-wisc/large_scale_ood)? 
```
wget http://pages.cs.wisc.edu/~huangrui/imagenet_ood_dataset/iNaturalist.tar.gz
wget http://pages.cs.wisc.edu/~huangrui/imagenet_ood_dataset/SUN.tar.gz
wget http://pages.cs.wisc.edu/~huangrui/imagenet_ood_dataset/Places.tar.gz
```

The default temperature for ID classification is 0.07 (L295, https://github.com/openai/CLIP/blob/main/clip/model.py). For OOD detection, we need a larger temperature (e.g., tau = 1) than the default one.

**Comment by burgerberlin** [comment]
Does the tau=1 mean parser.add_argument('--T', type=int, default=1,help='temperature parameter') in eval_ood_detection.py?
I think I used it right and I will examine the datasets you recommended, thank you.

**Comment by burgerberlin** [comment]
I greatly appreciate your assistance, which has enabled me to successfully replicate the results outlined in your paper. However, I still have inquiries regarding the softmax scaling approach discussed in your research. Specifically, I would like to understand the distinction, if any, between utilizing a value of tau=1 and employing the original softmax function. Based on my analysis, both mathematically and experimentally, they appear to yield identical outcomes. Could you please provide further clarification on this matter, either through mathematical explanations or empirical evidence? Thank you once again for your valuable support.

**Comment by alvinmingsf** [comment]
The original softmax function sets the temperature tau to a small value (e.g. 0.01). tau = 1 is not the default for zero-shot classification of CLIP. As a concrete example, you may check Figure 4 in the paper (also pasted below). When tau = 0.01 (second figure), the maximum softmax values for most ID inputs are concentrated around 1. When tau = 1 (third figure), the maximum softmax values for both ID and OOD are much smaller than 1.
<img width="1159" alt="Screen Shot 2023-11-28 at 2 41 11 AM" src="https://github.com/deeplearning-wisc/MCM/assets/20054386/d1a37c8d-ace9-4684-8d54-717ccbaed164">

**Comment by burgerberlin** [comment]
Sorry for replying to you so late. Thank you for your careful explanation and good work. I think I understand it completely. Thank you very much again.
