### ISSUE TITLE
How to train this network?

### ISSUE THREAD

**Issue by JiuqingDong** [deeplearning-wisc/MCM#2]
Hi. I replicated your work. It is training-free. Now I want to know how to train this network if I want to do few-shot learning.

**Comment by alvinmingsf** [comment]
Thanks for your interest! For few-shot learning with CLIP, there are several ways to train the network and still use MCM score for OOD detection: 1) tune an adaptor such as CLIP-Adaptor and Tip-AdaptorF (https://github.com/gaopengcuhk/Tip-Adapter); 2) tune a set of soft prompts such as CoOp and CoCoOp (https://github.com/KaiyangZhou/CoOp). We ran some experiments and observe that under both 1) and 2), MCM gives very strong OOD detection performance.
