### ISSUE TITLE
What ImageNet dataset split?

### ISSUE THREAD

**Issue by orrzohar** [deeplearning-wisc/MCM#3]
Hi,
I was wondering - in your results, do you run on the entire ImageNet training script? validation? or both? (i.e., when you say to download the imagenet dataset into /datasets/ImageNet).

Also, I just wanted to point out that you reference a file (settings.yaml) that does not exist in the repo in the readme. 

Best,
Orr

**Comment by alvinmingsf** [comment]
Hi! Yes, datasets/ImageNet contains the whole ILSVRC-2012 (i.e., with two subfolders train/ and val/). 

Thanks very much for the comments! Removed settings.yaml in readme.

**Comment by orrzohar** [comment]
OK Great, thank you!

I was also wondering why you needed to evaluate on the ImageNet training set - as you are using a CLIP zero-shot classifier, isn't ImageNet-val enough? 

Thank you!
Orr

**Comment by alvinmingsf** [comment]
Sorry for the confusion. The evaluation protocol is standard where for zero-shot CLIP with MCM score, as you said, we only need to use the val set of ImageNet. The train split is used for other baselines that require fine-tuning or OOD methods such as Mahalanobis score that use the training set to estimate classwise mean and covariance matrices.


If you would like to use MCM in the fine-tuning setting, you can use the training set to 1) tune an adaptor such as CLIP-Adaptor and Tip-AdaptorF (https://github.com/gaopengcuhk/Tip-Adapter); or 2) tune a set of soft prompts such as CoOp and CoCoOp (https://github.com/KaiyangZhou/CoOp).
