### ISSUE TITLE
missing requirments

### ISSUE THREAD

**Issue by orrzohar** [deeplearning-wisc/MCM#4]
Hi,
you seem to be missing some requirements, e.g., sklearn,
do you have an up-to-date requirements file?

**Comment by alvinmingsf** [comment]
Thanks for pointing out! A few more commonly used packages are needed such as scikit-learn, pandas, and tqdm. Just updated Readme.

**Comment by orrzohar** [comment]
& chardet
Just wanted to let you know

**Comment by alvinmingsf** [comment]
Thanks for the info! I noticed that I do not have chardet installed in the env. It's possible that this is due to a version difference. Will double-check and update
