### ISSUE TITLE
WordNet ID --> Class Name Mismatch?

### ISSUE THREAD

**Issue by inkawhich** [deeplearning-wisc/MCM#6]
Hello,

Thanks for releasing your ImageNet splits, very helpful. I am noticing some mismatches between the WordNet offsets ('n######') and the class names you have listed in both the paper and in the data/*.csv files.

E.g., in ImageNet20:
n01631663 is 'eft' according to WordNet but you have it as 'zebra'
n02391049 is 'zebra' according to WordNet but you have it as 'frilledlizard'

I have also visually verified that the WordNet classes are correct.

If this is a typo, I think this would be worth fixing because in zero-shot you would be creating the class prototype with TextTower('this is a photo of a frilledlizard') and expecting alignment with VisionTower(\<photo of a zebra\>).

Do you notice this issue on your end? 

Nate

**Comment by alvinmingsf** [comment]
Thanks very much for pointing out! The class names in the csv file and common.py for n01631663 and n02391049 are now fixed. I will double-check if there are additional mismatches
