### ISSUE TITLE
About stanford cars and new experiment results

### ISSUE THREAD

**Issue by xiapeng1110** [deeplearning-wisc/MCM#8]
Hi, thank you very much for your great work. 

But I found that the dataset `stanford cars` is no longer available `404 Not Found` for downloading through the [url](http://ai.stanford.edu/~jkrause/cars/car_dataset.html). Could you please copy a compressed package of the dataset to google drive? Thanks very much.

Also, you mentioned in other issues that you ran some experiments and observe that under both 1) tune an adaptor such as CLIP-Adaptor and Tip-AdaptorF; and 2) tune a set of soft prompts such as CoOp and CoCoOp, MCM gives very strong OOD detection performance. Could you please share your code or experiment results? Thanks again.

**Comment by alvinmingsf** [comment]
Thanks for your interest in our work! It appears that the official link for Stanford Cars is down. Here is a Google Drive link to the tar ball: https://drive.google.com/file/d/12SGFvVBHvJM-czeK-Mw3t0OcOmh8uFnO/view?usp=share_link. Please understand that here we mainly address issues related to the MCM codebase. While parameter-efficient tuning methods are quite interesting but out of the current scope.

**Comment by xiapeng1110** [comment]
Understand. Thanks for your help.
